### ISSUE TITLE
plot does not update when switching policy estimates

### ISSUE THREAD

**Issue by fhoces** [BITSS-OPA/opa-deworming#75]
when switching to a new policy estimate under the all assumptions tab, produces a new plot in that tab. But it does not update the plot in the other two tabs.

**Comment by AleksandraMaa** [comment]
Hi Fernando,

I saw the tag here, and I'm wondering what the expectations are for the
interaction between the three plots.

Is it supposed to update all three at the same time, no matter which tab
you change the inputs under? I changed this before because I thought they
were supposed to be 3 plots independent of changes under each tab. A little
bit of clarification on this would be much appreciated.

Happy Thanksgiving!

Best,
Aleksandra

**Comment by fhoces** [comment]
Hi Aleksandra, 
Ideally I would like for all three plots to react simultaneously for any input. 
Also, I am adding a bunch of issues now, but I do not expect you to work on them until next week. 
Happy thanks giving too!
Best, 
Fernando
