### ISSUE TITLE
SD font is too big in some cases

### ISSUE THREAD

**Issue by fhoces** [BITSS-OPA/opa-deworming#78]
see for example: SD of lambdas in A1. Tax revenue

**Comment by keanulim123** [comment]
I'm not seeing the differences between the font sizes of the text for the SDs of lambdas in the example and the text for the SDs of other parameters below it. I've linked a screenshot to what I'm seeing. I think it seems bigger due to the size/aesthetic of the two different input objects.

![Screenshot 2020-11-27 132610](https://user-images.githubusercontent.com/71524294/100485227-23ee5300-30b4-11eb-9e93-86626c2a809e.jpg)

**Comment by fhoces** [comment]
I might have fix that one please check all SDs to make sure all look the same

**Comment by keanulim123** [comment]
Did a quick check and it seems like they all look the same. Relatedly, there seems to be new parameters that are missing SDs (or are just not showing up when clicking the button).
