### ISSUE TITLE
combine variables from key assumptions and all assumptions

### ISSUE THREAD

**Issue by fhoces** [BITSS-OPA/opa-deworming#81]
all three variables from key assumptions: cost, prevalence and length are also present in all assumptions. Please figure out a way to modify the same input in two different tabs. Probably something to do with `observe`.

**Comment by keanulim123** [comment]
I'm not quite sure what you mean by this could you please clarify? When I modify prevalence and length in the Key Assumptions tab, the values also change in the All Assumptions tab and vice versa. The cost parameter is the only parameter that this is not true for. I think this is because the values for prevalence and length are used in both tabs while there is a unique value (costs2_ea_in) for the cost parameter in the Key Assumptions tab.

**Comment by AleksandraMaa** [comment]
this has been fixed now except for the cost :)

**Comment by fhoces** [comment]
could you merge to master?

**Comment by fhoces** [comment]
It might require some work to merge. I can do it. Are you both done with the reorg?

**Comment by keanulim123** [comment]
Yep! I think you merged the pull request I submitted that contained our reorg.

**Comment by AleksandraMaa** [comment]
Yeah! Do you need me to merge it? I thought the synchronized version was
merged. If not, I could try merging it. The branch name is plotsyncing.

**Comment by fhoces** [comment]
Done!
